"""create messages table

Revision ID: 13eb8344d8a1
Revises: 
Create Date: 2026-04-20 11:50:21.081304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13eb8344d8a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('role', sa.Enum('USER', 'BOT', name='role'), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('context', sa.Enum('WAITING_MESSAGE_1', 'WAITING_MESSAGE_2', 'WAITING_MESSAGE_3', 'WAITING_MESSAGE_4', 'WAITING_MESSAGE_5', name='context'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
