import enum

class Context(enum.Enum):
     WAITING_MESSAGE_1 = "WAITING_MESSAGE_1"
     WAITING_MESSAGE_2 = "WAITING_MESSAGE_2"
     WAITING_MESSAGE_3 = "WAITING_MESSAGE_3"
     WAITING_MESSAGE_4 = "WAITING_MESSAGE_4"
     WAITING_MESSAGE_5 = "WAITING_MESSAGE_5"
